### PR TITLE
make logo transparent background, change font to #414042 so can be se…

### PR DESCRIPTION
**Pull request by timkpaine**
…en on github dark background

### CODE REVIEW

**Comment by timkpaine** [comment]
from `ipyregulartable`, before:
Screen Shot 2021-01-16 at 10 23 45 PM

After on dark:
Screen Shot 2021-01-16 at 10 28 50 PM

After on light:
Screen Shot 2021-01-16 at 10 28 54 PM

**Comment by timkpaine** [comment]
feel free to close if you prefer the original

**Comment by timkpaine** [comment]
link to verify https://github.com/timkpaine/regular-table/blob/logotransparent/logo.png

**Comment by texodus** [comment]
Thanks for the PR!  I think this looks good!

**Pull request merged**
